In [1]:
import numpy as np


In [2]:
arr=np.array([1,2,3,4,5,6,7])

In [3]:
print(arr)    #print the whole list

[1 2 3 4 5 6 7]


In [4]:
arr   #description of variable 

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
arr=np.arange(1,10,1)

In [6]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
matrix=arr.reshape(3,3)

In [8]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
matrix1=arr.reshape(3,4)

ValueError: cannot reshape array of size 9 into shape (3,4)

In [10]:
arr=np.arange(1,7,1)

In [11]:
print(arr)

[1 2 3 4 5 6]


In [12]:
print(arr)

[1 2 3 4 5 6]


In [13]:
matrix=arr.reshape(3,2)

In [14]:
print(matrix)

[[1 2]
 [3 4]
 [5 6]]


In [15]:
print(arr)

[1 2 3 4 5 6]


In [16]:
arr1=np.array({1:"A",2:"B"})

In [17]:
import numpy as np


In [18]:
arr1=np.array({1:"A",2:"B"})

In [19]:
print(arr1)

{1: 'A', 2: 'B'}


In [20]:
arr1[1] #in dict indexing is not there for this we have to use loop

IndexError: too many indices for array

In [21]:
arr1                                                 #defines that it is array type

array({1: 'A', 2: 'B'}, dtype=object)

In [22]:
dt=np.dtype(np.int64)                                       #object of int64

In [23]:
for x in arr1:
    print(x)

TypeError: iteration over a 0-d array

In [24]:
dt1=np.dtype('i4')                     #i4=int64

In [25]:
student=np.dtype([('name','S20'),('age','i1'),('marks','f4')])          #s20=stirng of 20 character, i1=int8,   f4=float64

In [26]:
type(student)

numpy.dtype

In [27]:
s1=np.array([('dskjdkjhkhdijdkjdddjdjwqld',21,67)],dtype=student)

In [28]:
print(s1)

[(b'dskjdkjhkhdijdkjdddj', 21, 67.)]


In [29]:
#here  b denotes byte

In [30]:
student1=np.dtype([('name','S20'),('age','i1'),('marks','i4')])  

In [31]:
s2=np.array([('dskjdkjhkhdijdkjdddjdjwqld',21,67.0781)],dtype=student1)

In [32]:
print(s2)

[(b'dskjdkjhkhdijdkjdddj', 21, 67)]


In [33]:
a1=np.arange(1,13,1)

In [34]:
print(a)

NameError: name 'a' is not defined

In [35]:
print(a1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [36]:
m1=a1.reshape(4,3)

In [37]:
print(m1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [38]:
                                       # 1 4 7 10 is column 0 and 1 2 3 is row 0    and so on

In [39]:
m1[2,2]                               # first one is for row       and  second one is for col.

9

In [40]:
m1[1:3,1:3]                               # it creates loop itself internally      
                                          #  1:3 is for row 1 to 2 and  1:3 is row 1 to 2

array([[5, 6],
       [8, 9]])

 for x in range(1,3):
    for y in range(1,3):
        print(m1[x][y],end=" ")
    print() 

In [41]:
for x in range(1,3):
    for y in range(1,3):
        print(m1[x][y],end=" ")
    print()

5 6 
8 9 


In [42]:
print(m1.T)                                 #transpose matrix

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [43]:
print(m1.mean())

6.5


In [44]:
m1*0

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [45]:
m1+2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [46]:
print(np.zeros([3,3]))                  #by default it create floating value

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [47]:
print(np.ones([3,3]))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [48]:
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [49]:
m1=np.arange(1,10,1).reshape(3,3)
m2=np.arange(2,20,2).reshape(3,3)
print(m1)
print(m2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [50]:
m3=np.dot(m1,m2)                        # dot is method used  for matrix multiplication

In [51]:
m3

array([[ 60,  72,  84],
       [132, 162, 192],
       [204, 252, 300]])

In [52]:
print(np.add(m1,m2))

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [53]:
print(np.subtract(m2,m1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
print(np.subtract(m1,m2))

[[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]]


In [55]:
print(np.multiply(m1,m2))                      # here multiply func will multiply element by element

[[  2   8  18]
 [ 32  50  72]
 [ 98 128 162]]


In [56]:
print(np.divide(m1,m2))

[[0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]


In [57]:
m4=np.array([[1,2,3],[3,2,4],[4,5,6]])

In [58]:
print(m4)

[[1 2 3]
 [3 2 4]
 [4 5 6]]


In [59]:
m4.size

9

In [60]:
1 2 3 4 
4 5 6 7 
9 5 8 6                                    #print 5 6 7 and 5 8 6 and 9 6 3
8 9 6 3

SyntaxError: invalid syntax (<ipython-input-60-9b8e89cc366a>, line 1)

In [61]:
m5=np.array([1,2,3,4,4,5,6,7,9,5,8,6,8,9,6,3])

In [62]:
print(m5)

[1 2 3 4 4 5 6 7 9 5 8 6 8 9 6 3]


In [63]:
m6=m5.reshape(4,4)

In [64]:
m6

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [9, 5, 8, 6],
       [8, 9, 6, 3]])

In [65]:
print(m6[1:4,1:4])

[[5 6 7]
 [5 8 6]
 [9 6 3]]


In [66]:
m6[1:3,1:3]

array([[5, 6],
       [5, 8]])

In [67]:
m6[1:3]

array([[4, 5, 6, 7],
       [9, 5, 8, 6]])

In [68]:
m6[1:2]

array([[4, 5, 6, 7]])

In [69]:
m6[1:3,1:3]

array([[5, 6],
       [5, 8]])

In [70]:
mat=np.arange(1,17).reshape(4,4)
print(mat)
print(np.hsplit(mat,2))
print(np.vsplit(mat,2))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


In [71]:
mat=np.arange(1,17).reshape(4,4)
print(mat)
print(np.hsplit(mat,4))
print(np.vsplit(mat,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]]), array([[ 4],
       [ 8],
       [12],
       [16]])]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]]), array([[13, 14, 15, 16]])]


In [72]:
a=np.array([1,2,3])
print(type(a))
print(a.shape)
b=np.array([[1,2],[3,4]])
c=np.array([[1,2],[3,4],[5,6]])
d=np.array([[1,2]])
print(type(b))
print(b.shape)
print(c.shape)
print(d.shape)

<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
(2, 2)
(3, 2)
(1, 2)


In [73]:
#here (3,) represents  3 column and 1 row    and (2,2) represents 2 column and 2 row 

In [74]:
print(a[0],a[1],a[2])

1 2 3


In [75]:
a[0]=5
print(a)

[5 2 3]
